config/routes.rb
JcropAhead::Engine.routes.draw do
  resources :attachments

end

app/models/jcrop_ahead/attachment.rb
module JcropAhead
  class Attachment < ActiveRecord::Base
    belongs_to :attachable, :polymorphic => true

	#validates_presence_of :image
	validates_presence_of :attachable_id
	validates_presence_of :attachable_type

	mount_uploader :image, JcropAheadUploader
	
	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

	after_update :crop_image
  
	def crop_image
	  image.recreate_versions! if crop_x.present?
	end

  end
end

app/controllers/jcrop_ahead/application_controller.rb
module JcropAhead
  class ApplicationController < ActionController::Base
  end
end

app/controllers/jcrop_ahead/attachments_controller.rb
require_dependency "jcrop_ahead/application_controller"

module JcropAhead
  class AttachmentsController < ApplicationController
    before_action :set_attachment, only: [:show, :edit, :update, :destroy, :jcrop]
    before_action :find_or_initialize, :only => [:new]
    # GET /attachments
    def index
      @attachments = Attachment.all
    end

    # GET /attachments/1
    def show
    end

    # GET /attachments/new
    def new
      
    end

    def jcrop
      
    end

    # GET /attachments/1/edit
    def edit
    end

    # POST /attachments
    def create
      @attachment = Attachment.new(attachment_params)

      if @attachment.save
        if params[:attachment][:image].present?
          redirect_to jcrop_attachment_path(@attachment)
        else
          redirect_to context_url(@attachment), notice: 'Imagen ha sido creada con éxito.'
        end
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /attachments/1
    def update
      if @attachment.update(attachment_params)
        if params[:attachment][:image].present?
          redirect_to jcrop_attachment_path(@attachment)
        else
          redirect_to context_url(@attachment), notice: 'Imagen ha sido actualizada con éxito.'
        end
      else
        render action: 'edit'
      end
    end

    # DELETE /attachments/1
    def destroy
      url = context_url(@attachment)
      @attachment.destroy
      redirect_to url, notice: 'Imagen ha sido eliminada con éxito.'
    end

    private

      def find_or_initialize
        @attachment = Attachment.find_or_initialize_by(:attachable_id => params[:attachable_id], :attachable_type => params[:attachable_type])
      end

      def context_url(object)
        model_object = object.attachable
        eval("#{model_object.class.name.pluralize.downcase}_path")
      end


      # Use callbacks to share common setup or constraints between actions.
      def set_attachment
        @attachment = Attachment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def attachment_params
        params.require(:attachment).permit(:image, :attachable_id, :attachable_type, :remove_image, :crop_x, :crop_y, :crop_w, :crop_h)
      end
  end
end

app/helpers/jcrop_ahead/application_helper.rb
module JcropAhead
  module ApplicationHelper
  end
end

app/helpers/jcrop_ahead/attachments_helper.rb
module JcropAhead
  module AttachmentsHelper
  end
end

app/views/jcrop_ahead/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
    <%= f.hidden_field :attachable_id %>
    <%= f.hidden_field :attachable_type %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jcrop_ahead/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/jcrop_ahead/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Attachable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.image %></td>
        <td><%= attachment.attachable %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/jcrop_ahead/attachments/jcrop.html.erb
<%= link_to("Cancelar", root_path, :class =>"btn btn-default" ) %>

<h1>Recortar imagen</h1>

<%= image_tag(@attachament.image_url(:large), :id =>"crop_image") %>


<h4>Preview</h4>
<div style="width:220px; height:100px; overflow:hidden">
  <%= image_tag @attachament.image.url(:large), :id => "preview" %>
</div>


<hr>

<%= form_for @attachament do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jcrop_ahead/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/jcrop_ahead/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @attachment.image %>
</p>

<p>
  <strong>Attachable:</strong>
  <%= @attachment.attachable %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/layouts/jcrop_ahead/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JcropAhead</title>
  <%= stylesheet_link_tag    "jcrop_ahead/application", media: "all" %>
  <%= javascript_include_tag "jcrop_ahead/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>